apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{.Name}}-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{.Name}}-cr
subjects:
- kind: ServiceAccount
  name: {{.Name}}-sa
  namespace: {{.Namespace}}