apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
  labels:
    group: "service-discovery"
    test: {{.TestClientLabel}}
    type: {{.TypeLabelValue}}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{.Name}}
  template:
    metadata:
      labels:
        group: "service-discovery"
        name: {{.Name}}
        test: {{.TestClientLabel}}
        type: {{.TypeLabelValue}}
    spec:
      # Use separate nodes to avoid consuming CPU/Memory resources on default
      # nodes where all deployments of the performance test run.
      nodeSelector:
        test-np: {{.TestClientNodeSelectorValue}}
      tolerations:
      - key: test-np
        operator: Equal
        value: {{.TestClientNodeSelectorValue}}
        effect: NoSchedule
      - key: "slo"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      containers:
      - name: net-policy-latency-client
        ports:
        - containerPort: {{.MetricsPort}}
          name: npdelaymetrics
          protocol: TCP
        imagePullPolicy: Always
        # image: gcr.io/k8s-staging-perf-tests/network-policy-enforcement-latency/policy-creation-enforcement-latency:v0.0.1
        image: docker.io/sanamsarath/policy-creation-enforcement-latency:v0.0.1
        command:
        - sh
        - -c
        - ./policy-creation-enforcement-latency
          -HostNamespace="{{.Namespace}}"
          -TargetLabelSelector="{{.TargetLabelSelector}}"
          -TargetNamespace="{{.TargetNamespace}}"
          -TargetPort={{.TargetPort}}
          -MaxTargets={{.MaxTargets}}
          -MetricsPort={{.MetricsPort}}
          -AllowPolicyName={{.AllowPolicyName}}
          -np_type={{.NetworkPolicy_Type}}
          -np_namespace={{.Namespace}} # change this value according to the namespace where the policy is created, verify policy-egress-allow-target-pods.yaml
        resources:
          requests:
            cpu: 200m
            memory: 100Mi
      serviceAccountName: {{.ServiceAccountName}}
