apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment
  namespace: busybox
  labels:
    app: busybox
    group: "service-discovery"
spec:
  replicas: 1000
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 0
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
        group: "service-discovery"
    spec:
      containers:
      - name: busybox
        image: mcr.microsoft.com/azurelinux/busybox:1.36
        imagePullPolicy: IfNotPresent
        command:
        - sleep
        - "3600"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      hostNetwork: false
      restartPolicy: Always
      nodeSelector:
        slo: "true"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: busybox
            topologyKey: kubernetes.io/hostname
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
