apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-redirect-target-deployment
  namespace: busybox
  labels:
    app: test-target
spec:
  replicas: 1000
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: test-target
  template:
    metadata:
      labels:
        app: test-target
    spec:
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
      hostNetwork: false
      restartPolicy: Always
      nodeSelector:
        slo: "true"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: test-target
            topologyKey: kubernetes.io/hostname
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists