{{ if not (eq .Networking_Type "cilium") }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-np
  namespace: test-np
  labels:
    type: test-np
spec:
  podSelector:
    matchLabels:
      type: test-np
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          net-pol-test: test-np
{{if .OnlyTargetNamespace}}
      namespaceSelector:
        matchLabels:
          k8s:io.kubernetes.pod.namespace: {{.TargetNamespace}}
{{else}}
      namespaceSelector: {}
{{end}}
{{else}}
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: test-np-cilium
  labels:
    type: test-np-cilium
spec:
  endpointSelector:
    matchLabels:
      type: test-np
  egress:
  - toEndpoints:
    - matchLabels:
        net-pol-test: test-np
{{if .OnlyTargetNamespace}}
        k8s:io.kubernetes.pod.namespace: test-np-2
{{end}}
{{if .L7Enabled}}
    toPorts:
    - ports:
      - port: "80"
        protocol: TCP
      rules:
        http:
        - method: GET
          path: /
{{end}}
{{end}}