apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: netperf
  name: {{.Name}}
  labels:
    group: network
spec:
  replicas: {{.Replicas}}
  selector:
    matchLabels:
      name: {{.Name}}
  template:
    metadata:
      labels:
        group: network
        name: {{.Name}}
    spec:
      serviceAccountName: {{.Name}}
      containers:
      - image: gcr.io/k8s-testimages/netperfbenchmark:0.3
        name: worker
        imagePullPolicy: IfNotPresent
        args:
          - --log_file=/var/log/cl2-netperf-worker.log
          - --logtostderr=false
          - --v=4
          - --udpClientExtraArguments=-b 750M
        resources:
          requests:
            cpu: "10m"
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
            - name: logs-volume
              mountPath: /var/log
      volumes:
        - name: logs-volume
          hostPath:
            path: /var/log

