kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{.Name}}
rules:
- apiGroups: ["clusterloader.io"]
  resources: ["networktestrequests"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
