apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: networktestrequests-rbac
subjects:
  - kind: ServiceAccount
    name: {{.Name}}
    namespace: {{.Namespace}}
roleRef:
  kind: ClusterRole
  name: {{.Name}}
  apiGroup: rbac.authorization.k8s.io
